#!/usr/bin/perl
use POSIX ":sys_wait_h";
if(@ARGV){
    if($ARGV[0] eq "start"){
       	lancerServeur() || exit 1;
	exit 0;
    }
    elsif($ARGV[0] eq "stop"){
	arreterServeur() || exit 1;
	exit 0;
    }
    elsif($ARGV[0] eq "status"){
	status();
    }
    else{
	die "Erreur: options disponibles: start, stop, status\n";
    }
}

sub enregistrerPID{
    #changer et mettre les ouvriers dans une table de hachage
    open(PID,">>/tmp/.comanche_pid");
    print PID "@_\n";
    close(PID);
}

sub lancerServeur{
    
    #lecture fichier de config
    lireConf();#hachage de conf $conf{clé}
    
    use Socket;
    ### création de la socket ###
    socket(SERVEUR,PF_INET,SOCK_STREAM,getprotobyname('tcp'));
    setsockopt(SERVEUR,SOL_SOCKET, SO_REUSEADDR,1);
    $mon_adresse = sockaddr_in ($conf{"port"},INADDR_ANY);
    bind(SERVEUR, $mon_adresse) || die ("bind");
    listen (SERVEUR, SOMAXCONN) || die ("listen");	
    print "Le serveur écoute sur le port $conf{\"port\"} et accepte $conf{\"clients\"} clients max\n";
    
    #création du répartiteur (qui acceptera les connexions)
    $repartiteur=fork;
    
    if($repartiteur==0){
	
	open(PID,">/tmp/.comanche_pid");
	print PID "$$\n";
	close(PID);
	# Gestion des connexions des clients 
	#et création des ouvriers
	$compteurClient=0;
	$nbRequetesRecues=0;
	$nbRequetesTraitees=0;
	%ouvriers;
	while(accept(CLIENT,SERVEUR) || die ("accept")){
	    $nbRequetesRecues++;
	    if($compteurClient < $conf{"clients"}){
		$compteurClient++;
		
		while(<CLIENT>){
		    print "$_";
		    $requeteClient.=$_;
		    if($_ =~ "^\r\n"){
			last;
		    }
		}
		##verifier la requete ##
		if($requeteClient =~ /GET (\/(.*)) HTTP\/1\.1/ ){
		    #la requete est conforme on recupère ce que le client demande
		    $requeteClient=$1;
		}
		else{
		    #si elle n'est pas bonne on renvoie une erreur 400
		    repondre400();
		    next;
		}
		
		##Création ouvrier##
		$pid=fork;
		if($pid == 0){
		    enregistrerPID "$$";
		    print "RESSOURCE:$requeteClient\n";
		    ##########traitement de la requete#####################

		    ### aller chercher le fichier ###

		    if($requeteClient=~/$conf{"route"}/){
			print "La route est bonne\n";
			
			$chemin=`echo $requeteClient | sed -r 's!$conf{"route"}!$conf{"to"}!'`;
			##$requeteClient=~s!$conf{route}!$conf{"to"}!; ## ne fonctionne pas
			print "le chemin est : $chemin\n";
		    }
		    else{
			print "Ca marche pas\n";
		    }
		    
		    ###
		    ###il faut encore vérifier si le chemin existe
		    ###
		    open(FICHIER , $chemin)|| repondre403();
		    while(<FICHIER>){
			chomp;
			$contenu.="$_</br>";
		    }
		    ###
		    ###fabrication de la reponse ###
		    $contenu="<html><head><meta charset=\'utf-8\'><title>$requeteClient</title></head><body>$contenu</body></html>";
		    print "$contenu\n";
		    $reponse="HTTP/1.1 200 OK\r\n\r\n$contenu\r\n\r\n";
		    
		    #on envoie la requete et on ferme le client
		    CLIENT->autoflush(1);
		    print CLIENT $reponse;
		    
		    close(CLIENT);
		    
		    
		    exit 0;
		}
		else{
		    $ouvriers{"$pid"}=1;
		    print "Nb clients : $compteurClient \n";
		    while(($termine=waitpid(-1, &WNOHANG))>0){
			delete $ouvriers{"$termine"};
			$nbRequetesTraitees++;
			$compteurClient--;
		    }
		    close(CLIENT);
		}
		
	    }
	    else{
		##trop de clients, service indisponible
		repondre503();
	    }	 
	}

	close(SERVEUR);
	exit;
	
    }
    else{
	close(SERVEUR);
    }
}

sub repondre200{}

sub repondre400{
    $contenu=creerPage("400 BAD REQUEST", "Erreur 400: Requête invalide");
    
    $reponse="HTTP/1.1 400 BAD REQUEST\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
}
sub repondre403{
    $contenu=creerPage("403 Forbidden", "Erreur 403: Forbidden");
    
    $reponse="HTTP/1.1 403 FORBIDDEN\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
    exit 0;
}
sub repondre404{
    
    $contenu=creerPage("404 NOT FOUND", "$requeteClient </br>Erreur 404: ressource non trouvée");
    
    $reponse="HTTP/1.1 404 NOT FOUND\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
    exit 0;
    
}
sub repondre405{
    $contenu=creerPage("405 METHOD NOT ALLOWED", "Erreur 405: method not allowed");
    
    $reponse="HTTP/1.1 405 METHOD NOT ALLOWED\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
    exit 0;
}
sub repondre415{
    $contenu=creerPage("415 UNSUPPORTED MEDIA TYPE", "$requeteClient </br>Erreur 415: média non supporté");
    
    $reponse="HTTP/1.1 415 UNSUPPORTED MEDIA TYPE\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
    exit 0;
}
sub repondre503{
    
    $contenu=creerPage("503 SERVICE UNAVAILABLE", "Erreur 503: Service indisponible");
    $reponse="HTTP/1.1 503 SERVICE UNAVAILABLE\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
    exit 0;
}
sub repondre505{
    
    $contenu=creerPage("505 HTTP VERSION NOT SUPPORTED", "$requeteClient </br> Erreur 505: version HTTP non supportée");
    
    $reponse="HTTP/1.1 505 HTTP VERSION NOT SUPPORTED\r\n\r\n$contenu\r\n\r\n";
    #on envoie la reponse et on ferme le client
    CLIENT->autoflush(1);
    print CLIENT $reponse;
    close(CLIENT);
    exit 0;
}
sub creerPage{
    
    my $titre=@_[0];
    my $corps=@_[1];
    my $contenu="";
    if($conf{"error"}){
	open(PAGE, "$conf{\"error\"}") || die "$conf{\"error\"} n'existe pas";
	while(<PAGE>){
	    $contenu.=$_;
	}
	
	$contenu=~s!<title>(.*)</title>!<title>$titre</title>!;
	$contenu=~s!<body>(.*)</body>!<body><h1>$corps</h1></br>\1</body>!;
    }
    else{
	$contenu="<html><head><meta charset=\'utf-8\'><title>$titre</title></head><body> <h1>$corps</h1> </body></html>";
    }
    return $contenu;
}

sub arreterServeur{
    close(CLIENT) ;
    close(SERVEUR);
    open(PID,"/tmp/.comanche_pid");
    while(<PID>){
	kill(SIGTERM,$_);
    }
    close(PID);
    
    open(PID, ">/tmp/.comanche_pid");
    print PID "";
    close(PID);
}


sub status{
    open(PID,"/tmp/.comanche_pid") || die "Erreur: ouverture /tmp/.comanche_pid";
    $pid=<PID>;
    if(! $pid){
	print "Le serveur n'est pas lancé\n";
    }
    else{
	print "$pid";
	#ajouter une ligne avec le nombre de requetes recues et le nombre de requetes traitees
	#ajouter une ligne avec le nombre d(ouvriers actif et la liste de ces ouvriers
    }
}
sub lireConf{
    %conf;
    open(CONFIG, "<comanche.conf") || die "Erreur lecture comanche.conf : $!";
    while(<CONFIG>){
	chomp($_);
	if($_ =~ /^#/ || $_ =~ /^$/){next;}
	if($_ =~ /^\s*set\s+(.+)\s+([^\s#]+)(?:\s*#.*)?$/){
	    $cle=$1;
	    $valeur=$2;
	    
	    if($cle =~ /port/){
		die "Erreur de configuration: port $valeur invalide" if $valeur <1 && $valeur>65535;
	    }
	    elsif($cle =~ /error/){
		die "Erreur de configuration: $valeur n'existe pas\n" unless -f $valeur;
		
	    }
	    elsif($cle =~ /index/){
		#la verification se fait lors du traitement d'une requête car ce fichier n'est pas forcément présent
	    }
	    elsif($cle =~ /logfile/){
		open(LOGFILE, ">>$valeur") || die "Erreur de configuration : logfile $valeur n'est pas disponible\n";
		close(LOGFILE) || die "Erreur fermeture $valeur\n";
	    }
	    elsif($cle =~ /clients/){
		die "Erreur de configuration: $cle $valeur n'est pas valide\n" unless $valeur =~ /\d+/;
	    }
	    else{
		die "Erreur de configuration: $cle n'est pas valide\n";
	    }
	    $conf{$cle}=$valeur;
	}
	elsif($_ =~ /^\s*route\s+(.*)\s+to\s+(.*)/){
	    
	    $conf{"route"}=$1;
	    $conf{"to"}=$2; 
	    
	}
	elsif($_ =~ /^\s*exec\s+(.*)\s+from\s+(.*)/){
	    
	    $conf{"exec"}=$1;
	    $conf{"from"}=$2;
	}
	else{
	    die "Erreur de configuration: la ligne $_ n'est pas valide\n";
	}
    }
}
